CREATE TABLE `spaced_review_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`learner_id` int NOT NULL,
	`item_type` enum('retry_fault','review_concept','repeat_simulation','explain_fault','practice_work_order','practice_communication','review_safety','review_reasoning') NOT NULL,
	`source_id` varchar(120) NOT NULL,
	`source_label` varchar(255) NOT NULL,
	`domain` varchar(40) NOT NULL,
	`skill` varchar(120),
	`reason` enum('missed_root_cause','slow_diagnostic','excess_hints','weak_reasoning','unsafe_action','failed_reflection','poor_operator_communication','vague_work_order','low_confidence','knowledge_decay','previous_needs_review') NOT NULL,
	`reason_detail` varchar(500) NOT NULL,
	`priority` enum('critical','high','medium','low') NOT NULL,
	`difficulty` int NOT NULL DEFAULT 3,
	`status` enum('pending','in_progress','completed','skipped') NOT NULL DEFAULT 'pending',
	`interval_days` int NOT NULL DEFAULT 0,
	`ease` int NOT NULL DEFAULT 250,
	`reps` int NOT NULL DEFAULT 0,
	`lapses` int NOT NULL DEFAULT 0,
	`due_at` timestamp NOT NULL,
	`last_attempt_result` enum('not_attempted','passed','failed','partial') NOT NULL DEFAULT 'not_attempted',
	`metadata` json,
	`mastered` boolean NOT NULL DEFAULT false,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `spaced_review_items_id` PRIMARY KEY(`id`)
);
