/**
 * AUTO-GENERATED — do not edit by hand.
 *
 * Regenerated by `pnpm db:export-decks` (scripts/export-published-decks.mjs),
 * which materializes decks published via the Authoring Studio (deck_drafts where
 * status = 'published') into this static module. Merged over the hand-authored
 * DECKS bundle in lessonCardContent.ts, so a published draft overrides any static
 * deck with the same "moduleSlug/lessonSlug" key on the next build.
 *
 * Empty by default until the first export runs.
 */
import type { LessonCardDeck } from "../learningCardTypes";

export const PUBLISHED_DECKS: Record<string, LessonCardDeck> = {};
